In [ ]:
import torch

In [ ]:
def calcularTrazaMatriz(matriz):
    """
    Calcula la traza de una matriz usando PyTorch.

    Argumentos:
    matriz -- un tensor de PyTorch de dimensiones (n, n)

    Retorna:
    traza -- un escalar que representa la traza de la matriz
    """
    diagonal = torch.diagonal(matriz)
    traza = torch.sum(diagonal)
    return traza

# Crear una matriz de ejemplo
matriz = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calcular la traza de la matriz
traza = calcularTrazaMatriz(matriz)

# Imprimir la traza
print(traza)

tensor(15)


In [ ]:
def traspuesta(matriz):
    return torch.tensor(list(map(list, zip(*matriz))))

# Crear una matriz de ejemplo
matriz = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calcular la transpuesta de la matriz
mTras = traspuesta(matriz)

# Imprimir la transpuesta
print(mTras)

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])


In [ ]:
# FALTA ESTA FUNCION
def adjunta(A):
  # Obtener el tamaño de la matriz
  n = A.shape[0]

  # Inicializar la matriz de cofactores
  C = torch.zeros(n, n)

  # Calcular los cofactores
  for i in range(n):
    for j in range(n):
      # Obtener la submatriz eliminando la fila i y la columna j
      A_ij = torch.cat((A[:i], A[i+1:]))
      A_ij = torch.cat((A_ij[:, :j], A_ij[:, j+1:]), dim=1)
      
      # Calcular el cofactor C_ij
      C_ij = ((-1)**(i+j)) * torch.det(A_ij.float())
      
      # Almacenar el cofactor en la matriz de cofactores
      C[i,j] = C_ij

  # Calcular la adjunta de la matriz
  adj_A = torch.transpose(C, 0, 1)
  return adj_A

# Crear una matriz de ejemplo
matriz = torch.tensor([[-3, 2, 0], [1, -1, 2], [-2, 1, 3]])

# Calcular la matriz adjunta
mAdj = adjunta(matriz)

# Imprimir la matriz adjunta
print(mAdj)

tensor([[-5.0000, -6.0000,  4.0000],
        [-7.0000, -9.0000,  6.0000],
        [-1.0000, -1.0000,  1.0000]])


In [ ]:
def inversa(matriz):
  adj = adjunta(matriz)
  tras = traspuesta(adj)
  det = torch.det(matriz.float())
  return traspuesta(tras/det)

# Crear una matriz ejemplo
matriz = torch.tensor([[2, 0, 1], [3, 0, 0], [5, 1, 1]])

# Calcular la matriz inversa
mInv = inversa(matriz)

# Imprimir la matriz inversa
print(mInv)

tensor([[ 0.0000,  0.3333, -0.0000],
        [-1.0000, -1.0000,  1.0000],
        [ 1.0000, -0.6667,  0.0000]])


In [ ]:
def covarianza(matriz):
    # Media de cada columna
    mean = torch.mean(matriz, dim=0)
    print(mean)

    # Cantidad de columnas = número de muestras
    n_samples = matriz.shape[0]

    #Cov(matriz) = 1/(n-1) * (matriz - mean(matriz))ᵀ * (matriz - mean(matriz))
    # La función utiliza el método T para transponer la matriz (matriz - mean) y el método mm para realizar la multiplicación de matrices.

    meanMatriz = matriz - mean
    cov = torch.mm(meanMatriz.T, meanMatriz) / (n_samples - 1)
    
    return cov

# Crear una matriz de ejemplo
matriz = torch.tensor([[2., 4., 6., 8.], [4., 8., 12., 16.], [12., 10., 5., 9.]])

# Calcular la covarianza
covarianza = covarianza(matriz)

# Imprimir la covarianza
print(covarianza)

tensor([ 6.0000,  7.3333,  7.6667, 11.0000])
tensor([[28.0000, 14.0000, -9.0000, -5.0000],
        [14.0000,  9.3333,  0.6667,  4.0000],
        [-9.0000,  0.6667, 14.3333, 16.0000],
        [-5.0000,  4.0000, 16.0000, 19.0000]])
